# Generated by Django 5.1 on 2024-09-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_figure_delete_historicalfigure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='stats',
        ),
    ]
