# Generated by Django 5.1 on 2024-09-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_figure_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='image_url',
        ),
    ]
